# This workflow updates GitHub Pages on the repo it is run from.

name: Update GitHub Pages

on:
  workflow_dispatch: # Manually trigger. Colon is required.
    inputs:
      samples_branch:
        description: 'Blockly-Samples branch to publish from (for examples)'
        required: true
        default: 'main'
        type: string
      core_branch:
        description: 'Blockly core branch to publish from (for plugins)'
        required: true
        default: 'main'
        type: string
  workflow_call: # Allow this workflow to be called from publish workflow.

permissions:
  contents: write # For checkout and push.

jobs:
  update-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Blockly-Samples
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.samples_branch || 'main' }}
          path: blockly-samples

      - name: Checkout Blockly
        uses: actions/checkout@v7
        with:
          repository: 'RaspberryPiFoundation/blockly'
          ref: ${{ inputs.core_branch || 'main' }}
          path: blockly

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: NPM install - Samples
        # Use CI so that we don't update dependencies in this step.
        working-directory: blockly-samples
        run: |
          npm ci

      - name: NPM install - Blockly
        # Use CI so that we don't update dependencies in this step.
        working-directory: blockly
        run: |
          npm ci

      - name: Pepare Plugins for deployment
        working-directory: blockly
        run: |
          npx nx reset && lerna run clean --scope '@blockly/*' && \
          lerna run build --scope '@blockly/*' && \
          lerna run predeploy --scope '@blockly/*'

      - name: Deploy to GH Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # deploys to the current repo,
        # so you can use this workflow from a fork to update your personal gh-pages
        working-directory: blockly-samples
        run: |
          npm run deploy:prepare
          git remote set-url origin https://git:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d gh-pages -t -u "github-actions-bot <support+actions@github.com>"
